### ISSUE TITLE
Add (*macho.File).GetObjCNonLazyCategories()

### ISSUE THREAD

**Issue by tux-mind** [blacktop/go-macho#10]
Thank you for this awesome library. It is simply fantastic!

I was wondering if it would be possible to add a `GetObjCNonLazyCategories` function to the `*macho.File` type, to get the categories from the `__DATA.__objc_nlclslist` section.

Thank you so much for your precious time and for making this library open :blush: 
-- tux_mind

**Comment by blacktop** [comment]
added in the last objc update/fix.  so should be good now!  feel free to close the issue if satisfied.  Thanks again!
