### ISSUE TITLE
Optionally suppress output to stdout

### ISSUE THREAD

**Issue by wagoodman** [blacktop/go-macho#11]
When using this lib I'm seeing `Unsupported code directory version Runtime, please notify author`. Based on how the library is being integrated (in a TUI environment) this notice mangles other output. Would you consider adding an API flag to globally disable or redirect these notices to another location (say a buffer that the caller can control)?

... and awesome library, highest-of-fives 🙌 .

**Comment by blacktop** [comment]
That's a good idea. I'll fix soon have you also tried my other tool gitHub.com/blacktop/ipsw ?

**Comment by blacktop** [comment]
sorry for the massive delay, I believe I turned the `fmt.Printf`s into return `fmt.Errorf`s so it shouldn't output the errors to stdout anymore, but I'll leave the issue open in case I missed one etc.

Thx again!

**Comment by blacktop** [comment]
Very cool! 

Ya that's been on my todo list for a while and I started a while back here - https://github.com/blacktop/go-macho/blob/master/pkg/codesign/codesign.go#L269
