### ISSUE TITLE
Unparsed Requirement Set

### ISSUE THREAD

**Issue by appsworld** [blacktop/go-macho#12]
A likely older implementation of LC_CODE_SIGNATURE is likely breaking codesign.ParseCodeSignature. The binary we encountered has a requirement set of 1 which translates to the host requirement set. It appears that requirement is currently not parsed and the fall through condition raises an error.

Entry Point:
https://github.com/blacktop/go-macho/blob/7d871575b3b1107812ee7882aad69d18b50ba974/file.go#L941

Error Point: 
https://github.com/blacktop/go-macho/blob/a30d3b0119c092bea1b80a2b2e7495cc53ad6434/pkg/codesign/types/requirement.go#L536

Reference: Requirement Sets
``` host—Applied to the direct host of this code module. Each code module in the hosting path can have its own host requirement, where the hosting path is the chain of code signing hosts starting with the most specific code known to be running, and ending with the root of trust (the kernel).``` [1]

File: https://www.virustotal.com/gui/file/17befb10e9c3d399cebc8d23d2355e9e3522f4a2cb83d2c7bf2b2726cbd255e9/details

1. https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/RequirementLang/RequirementLang.html``

**Comment by blacktop** [comment]
could you upload that file?

**Comment by appsworld** [comment]
Reuploading on VT does not work: https://www.hybrid-analysis.com/sample/17befb10e9c3d399cebc8d23d2355e9e3522f4a2cb83d2c7bf2b2726cbd255e9.

Falcon should suffice too

**Comment by blacktop** [comment]
am I supposed to be able to download the file from VT or hybrid?  I don't have accounts for either of these sites.  I think you can upload the file directly to this issue.

**Comment by appsworld** [comment]
[Acquisition.zip](https://github.com/blacktop/go-macho/files/10254204/Acquisition.zip)

**Comment by appsworld** [comment]
> am I supposed to be able to download the file from VT or hybrid? I don't have accounts for either of these sites. I think you can upload the file directly to this issue.

Yes, In lieu of downloading the file from VT/Hybrid I've uploaded the file to this ticket.

**Comment by blacktop** [comment]
should be fixed now.  Many thanks for alerting me and please keep these issues coming ;)

**Comment by appsworld** [comment]
Thanks for fixes :)
