### ISSUE TITLE
Selector pointer inside the __objc_selrefs

### ISSUE THREAD

**Issue by lateralusd** [blacktop/go-macho#17]
Hi, first thank you for this awesome library. I would like to know if it is possible to include the original pointer inside the `__objc_selrefs` for the selectors, something like:

```golang
type Selector struct {
        SelRefsPointer uint64 // this field would be new one
        VMAddr uint64
        Name   string
}
```

My use-case for this is that I am disassembling binaries and inside the disassembly I see the addresses inside the `__objc_selrefs` and adding this new field would make it easier to do lookups.

**Comment by blacktop** [comment]
Hello!

I have also built a disassembler around `go-macho` in my [blacktop/ipsw](https://github.com/blacktop/ipsw) project.

> https://blacktop.github.io/ipsw/docs/guides/macho#macho-disass

Here's it in action:

To get the `__objc_selrefs` section vmaddr

```bash
❯ ipsw macho info /tmp/apsd | grep __objc_selrefs
	sz=0x00003de8 off=0x001000e8-0x00103ed0 addr="0x1001000e8"-0x100103ed0               __DATA.__objc_selrefs    NoDeadStrip (LiteralPointers)
```

To look at the `__objc_selrefs` data

```bash
❯ ipsw macho dump /tmp/apsd 0x1001000e8 -v
   • Setting --count=20
0x1000b34a2
"0x1000baa6d"
0x1000baa4e
<SNIP>
```

To look it up in the selector references

```bash
❯ ipsw macho info /tmp/apsd --objc --objc-refs | grep -i 1000baa6d
0x001001000f0 => 0x001000baa6d: "APNSPackDecoder:ReceivedError:"
```

To see it in the disassembler *(used in the objc stubs)*

```bash
❯ ipsw macho info /tmp/apsd | grep __objc_stubs
	sz=0x0000ce00 off=0x0009d4e0-0x000aa2e0 addr=0x10009d4e0-0x1000aa2e0               __TEXT.__objc_stubs      PureInstructions|SomeInstructions
```
```bash
❯ ipsw macho disass /tmp/apsd -a 0x10009d4e0 -c 6
   • Loading symbol cache file...
```
```nasm   
0x10009d4e0:  01 03 00 f0   adrp     x1, 0x100100000
0x10009d4e4:  21 78 40 f9   ldr      x1, [x1, #0xf0] ; sel_APNSPackDecoder:ReceivedError:
0x10009d4e8:  11 02 00 f0   adrp     x17, 0x1000e0000
0x10009d4ec:  31 62 2a 91   add      x17, x17, #0xa98 ; __got._objc_msgSend
0x10009d4f0:  30 02 40 f9   ldr      x16, [x17]
0x10009d4f4:  11 0a 1f d7   braa     x16, x17
```
> NOTE: the sel ref addr is used and marked up to show the selector it references

**Comment by blacktop** [comment]
This is how to dump the selector ref table:
```golang
if selRefs, err := m.GetObjCSelectorReferences(); err == nil {
	fmt.Printf("\n@selectors refs\n")
	for off, sel := range selRefs {
		fmt.Printf("0x%011x => 0x%011x: %s\n", off, sel.VMAddr, sel.Name)
	}
} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
	log.Error(err.Error())
}
```

**Comment by blacktop** [comment]
so I am already encoding that info in the output, just in a `map`

**Comment by lateralusd** [comment]
Awesome, thank you for the comprehensive answer, it is all clear now. Ipsw and projects that you built around it are truly impressive
