### ISSUE TITLE
Parse fail

### ISSUE THREAD

**Issue by lilili87222** [blacktop/go-macho#18]
[test.zip](https://github.com/blacktop/go-macho/files/10411877/test.zip)

if info, err := m.GetObjCImageInfo(); err == nil {
			fmt.Println(info.Flags)
		} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
			log.Error(err.Error())
		}

**Comment by lilili87222** [comment]
error failed to read objc_class_t at vmaddr 0x10000d3c8: failed to read super class objc_class_t at vmaddr: 0x10000d3c8; MachO does not contain dyld chained fixups

```

package main

import (
	"errors"
	"fmt"
	"github.com/apex/log"
	"github.com/blacktop/go-macho"
)

func main() {
	m, err := macho.Open("test.macho")
	if err != nil {
		panic(err)
	}
	defer m.Close()
	showMacho(m)

	//fmt.Println(m.FileTOC.String())
}
func showMacho(m *macho.File) {
	verbose := false
	showObjcRefs := false
	if m.HasObjC() {
		if info, err := m.GetObjCImageInfo(); err == nil {
			fmt.Println(info.Flags)
		} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
			log.Error(err.Error())
		}
		if verbose {
			fmt.Println(m.GetObjCToc())
		}
		if protos, err := m.GetObjCProtocols(); err == nil {
			for _, proto := range protos {
				if verbose {
					fmt.Println(proto.Verbose())
				} else {
					fmt.Println(proto.String())
				}
			}
		} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
			log.Error(err.Error())
		}
		if classes, err := m.GetObjCClasses(); err == nil {
			for _, class := range classes {
				if verbose {
					fmt.Println(class.Verbose())
				} else {
					fmt.Println(class.String())
				}
			}
		} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
			log.Error(err.Error())
		}
		if cats, err := m.GetObjCCategories(); err == nil {
			for _, cat := range cats {
				if verbose {
					fmt.Println(cat.Verbose())
				} else {
					fmt.Println(cat.String())
				}
			}
		} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
			log.Error(err.Error())
		}
		if showObjcRefs {
			if protRefs, err := m.GetObjCProtoReferences(); err == nil {
				fmt.Printf("\n@protocol refs\n")
				for off, prot := range protRefs {
					fmt.Printf("0x%011x => 0x%011x: %s\n", off, prot.Ptr, prot.Name)
				}
			} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
				log.Error(err.Error())
			}
			if clsRefs, err := m.GetObjCClassReferences(); err == nil {
				fmt.Printf("\n@class refs\n")
				for off, cls := range clsRefs {
					fmt.Printf("0x%011x => 0x%011x: %s\n", off, cls.ClassPtr, cls.Name)
					// if verbose {
					// 	fmt.Println(cls.Verbose())
					// } else {
					// 	fmt.Println(cls.String())
					// }
				}
			} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
				log.Error(err.Error())
			}
			if supRefs, err := m.GetObjCSuperReferences(); err == nil {
				fmt.Printf("\n@super refs\n")
				for off, sup := range supRefs {
					fmt.Printf("0x%011x => 0x%011x: %s\n", off, sup.ClassPtr, sup.Name)
				}
			} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
				log.Error(err.Error())
			}
			if selRefs, err := m.GetObjCSelectorReferences(); err == nil {
				fmt.Printf("\n@selectors refs\n")
				for off, sel := range selRefs {
					fmt.Printf("0x%011x => 0x%011x: %s\n", off, sel.VMAddr, sel.Name)
				}
			} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
				log.Error(err.Error())
			}
			if verbose {
				if classes, err := m.GetObjCClassNames(); err == nil {
					fmt.Printf("\n@objc_classname\n")
					for vmaddr, className := range classes {
						fmt.Printf("0x%011x: %s\n", vmaddr, className)
					}
				} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
					log.Error(err.Error())
				}
				if methods, err := m.GetObjCMethodNames(); err == nil {
					fmt.Printf("\n@objc_methname\n")
					for vmaddr, method := range methods {
						fmt.Printf("0x%011x: %s\n", vmaddr, method)
					}
				} else if !errors.Is(err, macho.ErrObjcSectionNotFound) {
					log.Error(err.Error())
				}
			}
		}
	} else {
		fmt.Println("  - no objc")
	}
	fmt.Println()

}
```

**Comment by blacktop** [comment]
I'm confused by this issue, you are trying to analyze bad machos and it's erroring like it should.  Are you thinking that it shouldn't error and instead parse the corrupt or fake macho files?

**Comment by lilili87222** [comment]
This macho file was created by the latest Xcode .  exported from  iOS archive file

**Comment by lilili87222** [comment]
this ipa run on iOS device well

**Comment by lilili87222** [comment]
[test2.zip](https://github.com/blacktop/go-macho/files/10419916/test2.zip)


`2023/01/15 18:10:42 error failed to read objc_class_t at vmaddr 0x10000cfd8: failed to read super class objc_class_t at vmaddr: 0x10000cfd8; MachO does not contain dyld chained fixups

@protocol refs
0x001000080c0 => 0x0010000d188: UISceneDelegate
0x001000080c8 => 0x0010000d1e8: UIWindowSceneDelegate
0x001000080b0 => 0x0010000d0c8: NSObject
0x001000080b8 => 0x0010000d128: UIApplicationDelegate
2023/01/15 18:10:42 error failed to read objc_class_t at classref ptr: 0x8010000000000010; MachO does not contain dyld chained fixups
2023/01/15 18:10:42 error failed to read objc_class_t at superref ptr: 0x10000cfd8; MachO does not contain dyld chained fixups
`

**Comment by lilili87222** [comment]
I'm confused too.
I compile again, show other errors now

**Comment by blacktop** [comment]
I can add more "hardening" and defensive checks as to not crash on these weird MachOs but Apple's own tools just seem to give up:
```bash
❯ dyld_info -objc test.macho
test.macho [arm64]:
    -objc:
              type       vmaddr   data-vmaddr   name
```
```bash
❯ xcrun objdump --macho --objc-meta-data test.macho
test.macho:
Contents of (__DATA_CONST,__objc_classlist) section
Contents of (__DATA,__objc_classrefs) section
Contents of (__DATA,__objc_superrefs) section
Contents of (__DATA_CONST,__objc_protolist) section
Contents of (__DATA,__objc_selrefs) section
Contents of (__DATA_CONST,__objc_imageinfo) section
```

**Comment by lilili87222** [comment]
How about error? this error in the test2.zip .  it seems read super class information fail.

`2023/01/15 18:10:42 error failed to read objc_class_t at vmaddr 0x10000cfd8: failed to read super class objc_class_t at vmaddr: 0x10000cfd8; MachO does not contain dyld chained fixups

**Comment by blacktop** [comment]
@lilili87222 try the latest fix please

**Comment by lilili87222** [comment]
It works well now. Thanks very much .
Is there any example or test case show how to edit macho and save with this lib?

**Comment by blacktop** [comment]
Glad I could help and thank you for bringing this issue to my attention!

**Comment by blacktop** [comment]
This is the NEWEST example of how to use go-macho - https://github.com/blacktop/ipsw/blob/master/cmd/ipsw/cmd/macho/macho_patch.go

this lib was primarily created to support https://blacktop.github.io/ipsw/ and `ipsw` might do some of the things you need already so be sure to check it out!
