### ISSUE TITLE
symtab.Search() method doesn't work

### ISSUE THREAD

**Issue by BrytonLee** [blacktop/go-macho#22]
Hi,

Current symtabl.Search() has an imply that the symtab is already sorted,  in that case, it could use sort.search() binary search method for searching a specific symbol. However, symtab is not a sorted array. 

Thanks,
Chengdong

**Comment by blacktop** [comment]
Should be good now, thank you ❤️

**Comment by lilili87222** [comment]
UNKNOWN. for. arm64_32
fat.SubCPU.String(fat.CPU)  
lipo return arm64_32,but lib return UNKNOWN

**Comment by blacktop** [comment]
@lilili87222 this isn't your issue! 😏

**Comment by BrytonLee** [comment]
In fact, you cannot simply sort the symtab in place. :-(

Because symtab is already sorted by symbol->value (aka virtual address), and since there is no field for saving symbol stop address, so if someone needs that. It has to find the next symbol start address as current symbol's stop address.

If you sort symtabl in place, then people cannot easy to know which is next symbol and thus don't get stop address for current symbol. 

Thanks,
Chengdong

**Comment by blacktop** [comment]
I believe I have another fix in the latest  release that addresses your issue.

**Comment by BrytonLee** [comment]
Thank you!

Yes, e12feb398a4ca8a3f8992016da363af431122818 is functionally ok. But, I believe it is not necessary to use binary search  for this case, for performance matters,  before using binary search, the slice.Sort method is already an O(N) cost method. 

So I suggest to use O(N) search directly and without any additional copy.

**Comment by blacktop** [comment]
agreed and fixed in latest release

**Comment by BrytonLee** [comment]
Thank you.
