### ISSUE TITLE
UNKNOWN. for. arm64_32

### ISSUE THREAD

**Issue by lilili87222** [blacktop/go-macho#23]
fat.SubCPU.String(fat.CPU)
lipo return arm64_32,but lib return UNKNOWN

**Comment by blacktop** [comment]
do you have a binary I could see?

**Comment by lilili87222** [comment]
this

**Comment by lilili87222** [comment]
[error_macho.zip](https://github.com/blacktop/go-macho/files/10927415/error_macho.zip)

**Comment by blacktop** [comment]
thank you @lilili87222 ! ❤️

**Comment by lilili87222** [comment]
how to get the result like lipo ,neither of those two output not the same as lipo
ret = append(ret, strings.ToLower(fat.SubCPU.String(fat.CPU))) //result is [v8 v7k]
//ret = append(ret, fat.CPU.String()) //result is  [ARM64_32 ARM]
//lipo output [arm64_32 armv7k]


`func GetArches(file string) ([]string, error) {
	m, err := macho.Open(file)
	if err == nil {
		defer m.Close()
		arch := m.SubCPU.String(m.CPU)
		return []string{strings.ToLower(arch)}, nil
	}
	fats, err2 := macho.OpenFat(file)
	if err2 == nil {
		defer fats.Close()
		var ret []string
		for _, fat := range fats.Arches {
			ret = append(ret, strings.ToLower(fat.SubCPU.String(fat.CPU))) //result is [v8 v7k]
			//ret = append(ret, fat.CPU.String()) //result is  [ARM64_32 ARM]
			//lipo output [arm64_32 armv7k]
		}
		return ret, nil
	}
	return nil, err2
}`

**Comment by lilili87222** [comment]
Thank you for fast reply.
ARM+v7k=armv7k
but ARM64_32+v8 not= arm64_32
how to get the result like lipo ?

**Comment by blacktop** [comment]
```go
fmt.Println(strings.ToLower(fmt.Printf("%s %s", fat.CPU, fat.SubCPU.String(fat.CPU))))
```
does this not work?

**Comment by lilili87222** [comment]
fmt.Sprintf("%s %s", fat.CPU, fat.SubCPU.String(fat.CPU))
result :[ARM64_32 v8 ARM v7k]
ret1 := fmt.Sprintf("%s_%s", fat.CPU, fat.SubCPU.String(fat.CPU))
result:[ARM64_32_v8 ARM_v7k]

both are error.

**Comment by blacktop** [comment]
```bash
❯ ipsw macho info /Users/blacktop/Downloads/error_macho --header --arch v8
Magic         = 32-bit MachO
Type          = EXECUTE
CPU           = ARM64_32, v8
Commands      = 20 (Size: 1440)
Flags         = NoUndefs, DyldLink, TwoLevel, WeakDefines, PIE
```
```bash
❯ ipsw macho info /Users/blacktop/Downloads/error_macho --header --arch v7k
Magic         = 32-bit MachO
Type          = EXECUTE
CPU           = ARM, v7k
Commands      = 20 (Size: 1372)
Flags         = NoUndefs, DyldLink, TwoLevel, WeakDefines, PIE
````

**Comment by blacktop** [comment]
```bash
❯ otool -h -v /Users/blacktop/Downloads/error_macho
/Users/blacktop/Downloads/error_macho (architecture arm64_32):
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
   MH_MAGIC  ARM64_32        V8  0x00     EXECUTE    20       1440   NOUNDEFS DYLDLINK TWOLEVEL WEAK_DEFINES PIE
/Users/blacktop/Downloads/error_macho (architecture armv7k):
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
   MH_MAGIC      ARM        V7K  0x00     EXECUTE    20       1372   NOUNDEFS DYLDLINK TWOLEVEL WEAK_DEFINES PIE
```

**Comment by blacktop** [comment]
this looks right to me?

**Comment by blacktop** [comment]
if you look at `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/mach/machine.h`

The CPU is:
```c
#define CPU_TYPE_ARM64_32       (CPU_TYPE_ARM | CPU_ARCH_ABI64_32)
``` 
and the sub-cpu is:
```c
#define CPU_SUBTYPE_ARM64_32_ALL        ((cpu_subtype_t) 0)
#define CPU_SUBTYPE_ARM64_32_V8 ((cpu_subtype_t) 1)
```

So the CPU is `ARM64_32` `ARM64_32_V8` I have chosen to represent this as `ARM64_32` `V8` which is also what `otool` does.

`lipo` is representing the exact same info as `arm64_32` however, there is 2 subcpu types for `arm64_32`: `ALL` and `V8` so to me `lipo` is wrong.  It was just a decision that the `lipo` developer made in how to represent the CPU.

I am not going to make `lipo` as it is wrong.

**Comment by blacktop** [comment]
If it is important to you to match `lipo` exactly you would have to create a "mapping" from my output to what `lipo`'s output is.

**Comment by lilili87222** [comment]
OK,Thanks very much.
