### ISSUE TITLE
get super class infomations fail

### ISSUE THREAD

**Issue by lilili87222** [blacktop/go-macho#26]
oc code 

`

#import <UIKit/UIKit.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <MobileCoreServices/UTCoreTypes.h>
@interface ViewController : UIViewController

@end

`

ipsw not display the super class infomations
ipsw macho info --obj 

@interface ViewController :  { // 0x2000095d0
/* instance methods */

-[ViewController viewDidLoad]; // 0x100005898
@end

**Comment by blacktop** [comment]
Does it work when you supply `-V` ?
`ipsw macho info --obj -V` ?

**Comment by blacktop** [comment]
I'd be curious to see a binary to replicate

**Comment by blacktop** [comment]
should be fixed, thank you! ❤️

**Comment by lilili87222** [comment]
That's  great.Thank you!
