### ISSUE TITLE
Failed to parse swift macho using macho.GetSwiftTypes

### ISSUE THREAD

**Issue by LYsir** [blacktop/go-macho#29]
A panic error occurs when using macho.GetSwiftTypes to read the swift information in the IOSSwiftApp002 file in the IOSSwiftApp002.app package.
panic error：
`failed to read type at address 0x10000935c: failed to read type kind class flags(kind: class       generic: false, unique: true, version: 0, kind_flags: metadata_init:singleton|vtable): failed to read swift field: failed to read swift field record mangled type name; failed to read indirect context descriptor: failed to read swift context descriptor: EOF [recovered]`

Development and testing environment：
         macOS xcode version 14.2, iPhone 14 Pro simulator
Source code：
[IOSSwiftApp002_project_code.zip](https://github.com/blacktop/go-macho/files/13555332/IOSSwiftApp002_project_code.zip)
The app package where the macho file is located：
[IOSSwiftApp002_iPhone14Pro_simulator_app_package_.zip](https://github.com/blacktop/go-macho/files/13555338/IOSSwiftApp002_iPhone14Pro_simulator_app_package_.zip)
go-macho version : 1.1.182

**Comment by blacktop** [comment]
thank you! I'll look into it

**Comment by blacktop** [comment]
should be fixed, thank you! ❤️
