### ISSUE TITLE
Failed to read macho information using macho.GetObjCClasses

### ISSUE THREAD

**Issue by LYsir** [blacktop/go-macho#30]
An error occurred when using macho.GetObjCClasses to obtain information about macho files

macho file:
[test_Macho.zip](https://github.com/blacktop/go-macho/files/13610966/test_Macho.zip)

error:
failed to read objc_class_t at vmaddr 0x101819d50: pointer 0x101819d50 is not a bind

**Comment by blacktop** [comment]
thank you! I'll look into it

**Comment by blacktop** [comment]
should be fixed, thank you! ❤️

**Comment by blacktop** [comment]
That MachO had pretty insane c++ types in the ObjC properties, thx again for reporting 👍
