### ISSUE TITLE
Error during decoding some MachO: failed to read parseSymtab: invalid name in symbol table '40393' in record at byte 0xc78

### ISSUE THREAD

**Issue by NyaMisty** [blacktop/go-macho#42]
### What happened?

Go-macho cannot load and parse this MachO, but IDA Pro can. 
It's a big file, so splitted it into two parts:
[com.hotchaipro.matchsolitaire.001.txt](https://github.com/blacktop/go-macho/files/14878558/com.hotchaipro.matchsolitaire.001.txt)
[com.hotchaipro.matchsolitaire.002.txt](https://github.com/blacktop/go-macho/files/14878556/com.hotchaipro.matchsolitaire.002.txt)

Please use them by 
```
cat com.hotchaipro.matchsolitaire.001.txt com.hotchaipro.matchsolitaire.002.txt > com.hotchaipro.matchsolitaire
```

### How can we reproduce this?

The MachO is enclosed above.

### go-macho version

```bash
v1.1.193
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NyaMisty** [comment]
There's also another binary triggering this error:
error: `failed to read parseSymtab: invalid name in symbol table '41659' in record at byte 0xc60`
attachment: 
[CmmApp.txt](https://github.com/blacktop/go-macho/files/14878569/CmmApp.txt)

**Comment by NyaMisty** [comment]
Note these apps are all directly downloaded from AppStore, not manually crafted.

**Comment by blacktop** [comment]
Please try latest release

**Comment by NyaMisty** [comment]
> Please try latest release

Thanks! Finally got time to test, and it worked well!
