### ISSUE TITLE
facing error : "invalid magic number in record at byte 0x0"

### ISSUE THREAD

**Issue by kushalagrawal** [blacktop/go-macho#5]
I am trying to validate the existing application like firefox. It is failing with error: "invalid magic number in record at byte 0x0"
When I am trying with otool it is giving magic number as 

Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           2    34       4688 0x00a18085

Go is a very new language to me so could not understand much code. And Not sure what is causing this issue. can you help me in understanding and troubleshooting this.

**Comment by StarHack** [comment]
@kushalagrawal 
Without seeing your code, we can make assumptions all day long. You probably had something like this:

**Example 1:**
```go
package main

import (
	"fmt"

	"github.com/blacktop/go-macho"
)

func main() {
	m, err := macho.Open("firefox")
	if err != nil {
		panic(err)
	}

	fmt.Println(m)
}
```

**Result:**
```
panic: invalid magic number in record at byte 0x0

goroutine 1 [running]:
main.main()
	/Users/redacted/src/custom/macho/macho.go:13 +0x85
```

This happens because your input file is a [Fat binary](https://en.wikipedia.org/wiki/Fat_binary) and might contain support for multiple architectures. You probably want to use the function `OpenFat` instead.

**Example 2:**
```go
package main

import (
	"fmt"

	"github.com/blacktop/go-macho"
)

func main() {
	m, err := macho.OpenFat("firefox")
	if err != nil {
		panic(err)
	}

	fmt.Println(m)
}
```

**Result:**

```
Magic         = 64-bit MachO
Type          = Exec
CPU           = Amd64, x86_64 
Commands      = 36 (Size: 5000)
Flags         = NoUndefs, DyldLink, TwoLevel, PIE
...
033: LC_LOAD_DYLIB               /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (1109.60.2)
034: LC_RPATH                    @executable_path/../Frameworks
035: LC_FUNCTION_STARTS          offset=0x002a34d8-0x002a68f0 size=13336
036: LC_DATA_IN_CODE             offset=0x002a68f0-0x002a68f0 size=    0 entries=0
037: LC_CODE_SIGNATURE           offset=0x002ad9e0-0x002baf90 size=54704
```

From there we'd proceed working with a particular architecture, for example:

```go
for _, arch := range m.Arches {
	if arch.CPU.String() == "AARCH64" {
		fmt.Println("Apple Silicon")
	}
}
```

And from there you may deep dive into the depths of the Mach-O structure...

**Comment by blacktop** [comment]
Also if you just want to take a peek into MachOs vs. building your own solution checkout [ipsw](https://blacktop.github.io/ipsw/docs/commands/macho/) which is the reason I wrote this library in the first place :)

**Comment by kushalagrawal** [comment]
Thank you @StarHack. Yes, Indeed this was the reason for the failure.
