### ISSUE TITLE
Function Starts parse

### ISSUE THREAD

**Issue by 4cce1er** [blacktop/go-macho#7]
i want to parse Function Starts, to get all function address.
like Mach0View.
![image](https://user-images.githubusercontent.com/38617792/134312238-bb85905d-0699-4cde-bcaf-aec7968b97ac.png)
the Function Starts use [leb128](https://en.wikipedia.org/wiki/LEB128) to record offset.

Hopefully can support this feature, or tell me other ways to do it.

**Comment by 4cce1er** [comment]
https://github.com/gdbinit/MachOView/blob/d60a5c9502de14821bdbf54f07ab08a3c55b0d5a/capstone/arch/PowerPC/PPCGenDisassemblerTables.inc

**Comment by blacktop** [comment]
https://github.com/blacktop/go-macho/blob/a0c759c0e0bb99a7eb34f2737be3f475b59ac65a/file.go#L2162

**Comment by blacktop** [comment]
Or if you just want to see the function starts check out my ipsw tool here https://blacktop.github.io/ipsw/docs/commands/macho/

**Comment by 4cce1er** [comment]
thanks, My problem is solved! Best wishes to you
