### ISSUE TITLE
Possible typo in SourceVersion?

### ISSUE THREAD

**Issue by davendu** [blacktop/go-macho#8]
Hi. Recently we upgraded from `1.0.25` to `1.1.79`, which introduces a breaking change to some code like this:

```go
if v, ok := *machof.SourceVersion; ok {
    fmt.Println(v.SourceVersionCmd.Version)
}
```

I noticed in this line:

https://github.com/blacktop/go-macho/blob/9ee75aa756471b4b1a9b214216aa105857e1e0f5/cmds.go#L1475-L1480

The `SourceVersion` struct member is modified to `types.DylibCodeSignDrsCmd` from `types.DylibCodeSignDrsCmd` at [here](https://github.com/blacktop/go-macho/pull/4/commits/5061214dc6f555d58b7ce219f736ba43737606b9#diff-f61e7e343f4fb0c7677de6147c0970ec3f70313d66a7fe9a6f48e12211279c62L1142). Is this a typo, or we are using this field in wrong way?

Thanks.

**Comment by blacktop** [comment]
Thank you for notifying me!!! Should be fixed in latest release 👍
