### ISSUE TITLE
Report 'Unsupport code directory version' for fat MachO files

### ISSUE THREAD

**Issue by davendu** [blacktop/go-macho#9]
When analyzing a [sample file](https://filebin.net/0hvkdk3pfa6er8bq) (sha256: `906c55e45f37375c6ef8501a27f3e485bc75958ad4be73877000b30d14c99687`), this error shows on calling `OpenFat`:
```
Unsupported code directory version Runtime, please notify author
```

Seems the error is caused at [here](https://github.com/blacktop/go-macho/blob/master/pkg/codesign/codesign.go#L171). I read XNU's source code about it and found the corresponding [struct](https://github.com/apple/darwin-xnu/blob/main/osfmk/kern/cs_blobs.h#L180-L202).

However, when trying to implement it, it seems hard to decided if those fields should be read, since there does not have a good way to tell if those fields exists or not, unlike fields like `scatterOffset` and `teamOffset` which can be used to tell if `types.CodeDirectory.Scatter` and `types.CodeDirectory.TeamID` should be filled. Is there any recommendations so I can implement this part?

**Comment by blacktop** [comment]
awesome issue, thank you for letting me know!

**Comment by blacktop** [comment]
I believe I have fixed the issue now?  However, I'm not sure what to do with `SUPPORTS_LINKAGE` yet?  If you find a file that has that I'd be very interested.  Thanks again! 

Feel free to close the issue if it is fixed.

**Comment by davendu** [comment]
Thanks for the help, verified!

**Comment by davendu** [comment]
I'm still unable to find a file with `SUPPORTS_LINKAGE` but i will open a new issue if I found one.
